#!/usr/bin/env bash
# hyprcorners-launch.sh — regenerate config and restart hyprcorners
# Usage: hyprcorners-launch.sh WIDTH HEIGHT
# Example: hyprcorners-launch.sh 1920 1200

set -euo pipefail

# Args
W="${1:?Width missing}"
H="${2:?Height missing}"

# Paths
CONF="$HOME/.config/hypr/hyprcorners.toml"
LOG="$HOME/.cache/hyprcorners-launch.log"

mkdir -p "$(dirname "$CONF")" "$(dirname "$LOG")"

log() { printf '[%(%F %T)T] %s\n' -1 "$*" | tee -a "$LOG"; }

# Ensure hyprcorners binary exists (use PATH or mise fallback)
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
HYC="$(command -v hyprcorners || true)"
if [[ -z "$HYC" ]]; then
  HYC="$HOME/.local/share/mise/installs/rust/latest/bin/hyprcorners"
  [[ -x "$HYC" ]] || { log "ERROR: hyprcorners not found"; exit 1; }
fi

# Resolve nwg-drawer absolute path (avoids PATH issues at login)
DRAWER="$(command -v nwg-drawer || true)"
[[ -n "$DRAWER" ]] || DRAWER="/usr/bin/nwg-drawer"

# Kill any old hyprcorners
pkill -x hyprcorners 2>/dev/null || true
while pgrep -x hyprcorners >/dev/null; do sleep 0.1; done

# Write fresh config
cat > "$CONF" <<EOF
# Auto-generated by hyprcorners-launch.sh
timeout = 50
screen_width  = ${W}
screen_height = ${H}

[top_left]
radius = 10

[top_right]
radius = 10

[bottom_right]
radius = 10

[bottom_left]
radius     = 10
dispatcher = "exec"
args       = "${DRAWER}"
EOF

log "Wrote $CONF for ${W}x${H} (drawer=$DRAWER)"

# Start hyprcorners
nohup "$HYC" -c "$CONF" >>"$LOG" 2>&1 &
log "Started hyprcorners (PID=$!) with config $CONF"
